### ISSUE TITLE
Can't seem to build.

### ISSUE THREAD

**Issue by dineth-lochana** [segnoda/Coda#1]
I seem to be struggling to build the engine using PyInstaller. Could you make a release with the build.
PS- Does the engine support word wrapping.

**Comment by segnolin** [comment]
@lochana-Dineko 
Which platform do you mainly use? The source should work on any platform (Although some scaling issues on Windows and Linux). However, I only try to build the game on macOS. If you need the .app (macOS) release, I can build one. But the resources can't be modified after the build.
The engine does support word wrapping.

**Comment by segnolin** [comment]
@lochana-Dineko 
After trying, I'm sure that the project can be build on both Linux and Windows. Make sure you build the resources file beforehand by running `./pyrcc.sh` and install the latest dev version of pyinstaller (not the latest release version).

**Comment by dineth-lochana** [comment]
It builds alright. The first issue was my fault. On a side note even though there is a 'config' option, i can't access it and the script is empty. I wonder if you could add that as well and the engine would be complete,

btw- Are Mac executables supposed to be an. exe? I don't have a mac, so he doesn't know that.

**Comment by segnolin** [comment]
@lochana-Dineko 
The "Extra" and "Config" functions in main window, and "Skip" function in game engine are under development. I haven't write anything in config script so it's empty. I will accomplish these functions as soon as possible.
In macOS, the executable file structure is:
```
Coda.app    <-- folder
└── Contents
    ├── Frameworks
    ├── Info.plist
    ├── MacOS
    │   └── Coda    <-- executable
    └── Resources
        └── coda.icns    <-- icon
```
